plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.codeborne:selenide:7.18.0'
    testImplementation 'net.datafaker:datafaker:2.7.0'
}

test {
    useJUnitPlatform()
}